### ISSUE TITLE
Config Model

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/DashboardListDoc-widget#1]
Via the dashboard, when clicking on the cog icon to bring up the congif model, the info is not displayed correctly, and you need to scroll in tiny area (tested with firefox and chrome):

![my evolution site evo cms manager](https://user-images.githubusercontent.com/6113504/33794879-4e79e27c-dccc-11e7-9328-6a0ffb7fecd1.png)

The same happens if edit in model is selected.

**Comment by Nicola1971** [comment]
You need to update manager theme (default or evoflat) there are some recent updates on evo modal/pop .

**Comment by risingisland** [comment]
Thanks, works fine now.
