### ISSUE TITLE
Revert

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/DashboardListDoc-widget#4]
Why the revert, just out of curiosity?

**Comment by Nicola1971** [comment]
there was a big issue with new jquery-confirm and footables, so reverted to a stable version.

now is fixed

**Comment by Nicola1971** [comment]
the new confirm windows
https://youtu.be/ZejnTORrEBo

**Comment by risingisland** [comment]
Wow, pretty sexy confirm dialogs!
