### ISSUE TITLE
v2.0.5.1 issues

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/DashboardListDoc-widget#5]
Initially I had problems upgrading to this version. It ended up being that there was a name change in the plugin. Previously it was installed as "DashboardDocList", the latest installs as "DashboardListDoc".
I think I would also change the dependencies folder name as well to keep all names the same throughout.

Dialogs are only working for Duplicate Resource. 
It is not working with Delete/Undelete, Unpublish, or anywhere else. 
Also I am not presented with the default dialog either.
The new Escape key is working for the one dialog that is functioning.

**Comment by Nicola1971** [comment]
sorry there was a bug not visible in my chrome . tested in firefox , found and fixed.
please test and confirm.

**Comment by risingisland** [comment]
Deleted previous version, installed again, with both Chrome and FF.
Additional action buttons only show after going into config. and re-saving.
Will test a little more with both browsers. Not sure Dialogs are working properly on both, or if the config. save fixes this.
The same is happening with the module.

**Edit:** I just noticed that there is a single quote ' after the titles. This goes away after saving and everything seems to work as intended. 

![my evolution site evo cms manager](https://user-images.githubusercontent.com/6113504/34297445-1be535c0-e710-11e7-8c6a-933f36a495ac.png)
